on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS with ecs-cli & Elastic Beanstalk
env:
  EB_PACKEGE_S3_BUCKET_NAME: "elasticbeanstalk-eu-central-1-092663235681"
  EB_APP_NAME              : "multi-docker"
  EB_ENV_NAME              : "MultiDocker-env"
  DEPLOY_PACKAGE_NAME      : "MultiDocker-env-${{ github.sha }}.zip"
  AWS_REGION               : "eu-central-1"

jobs:
  build_test_push:    
    name: Test&build and push new images to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Git clone our REPO
        uses: actions/checkout@v2
      - name: Test phase 
        run: |
           docker build -t kosdockerid/react-test -f ./client/Dockerfile.dev ./client
           docker run kosdockerid/react-test npm test -- --coverage
      - name: Build phase  
        run: |    
           docker build -t kosdockerid/multi-client ./client
           docker build -t kosdockerid/multi-nginx ./nginx
           docker build -t kosdockerid/multi-server ./server
           docker build -t kosdockerid/multi-worker ./worker
      - name: Login to Dockerhub 
        run: echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_ID}} --password-stdin
      - name: Push images to Dockerhub 
        run: | 
           docker push kosdockerid/multi-client
           docker push kosdockerid/multi-nginx
           docker push kosdockerid/multi-server
           docker push kosdockerid/multi-worker
      
      - name: Create ZIP packege from REPO
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
               
      - name: Configure my AWS 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
          aws-region           : ${{ env.AWS_REGION }}      
       
      - name: Copy ZIP packege to S3
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME}}  s3://${{ env.EB_PACKEGE_S3_BUCKET_NAME }}/multi-docker/   
        
      - name: Print success msg
        run: echo "Zip-package copied successfully"      
      
  deployment:
    name: Deploy New version of App to ECS 
    runs-on: ubuntu-latest 
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install ECS-cli
        run: |
          sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          gpg --keyserver hkp://keys.gnupg.net --recv BCE9D9A42D51784F
          curl -Lo ecs-cli.asc https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest.asc
          gpg --verify ecs-cli.asc /usr/local/bin/ecs-cli
          sudo chmod +x /usr/local/bin/ecs-cli
          ecs-cli --version
      
