on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS with ecs-cli & Elastic Beanstalk
env:
  EB_PACKEGE_S3_BUCKET_NAME: "elasticbeanstalk-eu-central-1-092663235681"
  EB_APP_NAME              : "multi-docker"
  EB_ENV_NAME              : "MultiDocker-env"
  DEPLOY_PACKAGE_NAME      : "MultiDocker-env-${{ github.sha }}.zip"
  AWS_REGION               : "eu-central-1"

jobs:
  deployment:
    name: Deploy New version of App to ECS 
    runs-on: ubuntu-latest
    #needs: [build_test_push] 
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Create new EB_version of my Website
        run : |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APP_NAME }} \
          --source-bundle-information SourceLocation=${{ env.EB_PACKEGE_S3_BUCKET_NAME }}/multi-docker/"${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"
        
      - name: Deploy new EB version of application 
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENV_NAME }} --version-label "Ver-${{ github.sha }}"           
        
      - name: Print success CD msg
        run: echo "Deployment is done successfully" 
      
