on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS with ecs-cli docker-compose

jobs:
  deploy:
    name: Test&build and push new images
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install ECS-cli
        run: |
          curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          gpg --keyserver hkp://keys.gnupg.net --recv BCE9D9A42D51784F
          curl -Lo ecs-cli.asc https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest.asc
          gpg --verify ecs-cli.asc /usr/local/bin/ecs-cli
          sudo chmod +x /usr/local/bin/ecs-cli
          ecs-cli --version
          
          
